version: '2'
services:
  dnsmasq:
    image: mritd/dnsmasq
    container_name: dnsmasq
    restart: always
    ports:
      - "53:53/udp"
      - "53:53"
    volumes:
      - ./dnsmasq.hosts:/etc/dnsmasq.hosts
