version: '2'
services:
  filebeat:
    image: mritd/filebeat:5.6.3
    container_name: filebeat
    restart: always
    volumes:
      - ./filebeat.yml:/etc/filebeat/filebeat.yml
      - /data/docker/containers:/var/lib/docker/containers
