version: '2'
services:
  dragonite:
    image: dragonitenetwork/dragonite-java:0.3.1-alpine
    container_name: dragonite
    restart: always
    ports:
      - "152:152"
      - "153:153"    
      - "156:156"
    environment:
      - DCMD
    command: ${DCMD}
