version: '2'
services:
  shadowsocks:
    image: mritd/shadowsocks:3.0.8
    restart: always
    ports:
      - "23:23"
      - "139:139/udp"    
      - "135:135"
    environment:
      - SS_MODULE
      - SS_CONFIG
      - KCP_MODULE
      - KCP_CONFIG
    command: -m "$SS_MODULE" -s "$SS_CONFIG" -k "$KCP_CONFIG" -e "$KCP_MODULE" -x 
